services:
  # OpenTelemetry Collector - receives telemetry from Claude Code
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: claude-otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8889:8889"   # Prometheus metrics exporter
    networks:
      - claude-telemetry

  # Prometheus - stores metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: claude-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - claude-telemetry
    depends_on:
      - otel-collector

  # Grafana - visualization dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: claude-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - claude-telemetry
    depends_on:
      - prometheus

  # Loki - Optional log storage (commented out by default)
  # IMPORTANT: The standard OTEL Collector image doesn't support direct export to Loki.
  # If you need log collection, uncomment this service and use Promtail or Grafana Alloy
  # as an intermediary to send logs from OTEL Collector to Loki.
  #
  # loki:
  #   image: grafana/loki:latest
  #   container_name: claude-loki
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   volumes:
  #     - loki-data:/loki
  #   networks:
  #     - claude-telemetry

networks:
  claude-telemetry:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
  # loki-data:  # Uncomment if enabling Loki service above
